[build]
builder = "nixpacks"

[deploy]
startCommand = "node setup-database.js && node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production"
DB_TYPE = "postgresql"
DATABASE_URL = "postgresql://postgres:HdkNbFKYPIpqohGahElywJcjhMRJCIjc@postgres.railway.internal:5432/railway"
