[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run setup-db && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production"
DB_TYPE = "postgresql"
